=== DaniloJevtovic/poslovnaInformatika/project/instrumenti_placanja.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/instrumenti_placanja" xmlns:tns="http://www.example.org/instrumenti_placanja" elementFormDefault="qualified">
	<simpleType name="NazivSvrha">
		<restriction base="string">
			<pattern value="(([A-Z]|Č|Ć|Đ|Š|Ž|[a-z]|č|ć|đ|š|ž| ){1,35})(\n([A-Z]|Č|Ć|Đ|Š|Ž|[a-z]|č|ć|đ|š|ž| ){1,35}){0,2}"></pattern>
		</restriction>
	</simpleType>
	<simpleType name="SifraPlacanja">
		<restriction base="short">
			<totalDigits value="3"></totalDigits>
		</restriction>
	</simpleType>
	<simpleType name="Valuta">
		<restriction base="string">
			<pattern value="[A-Z]{3}"></pattern>
		</restriction>
	</simpleType>
	<simpleType name="Iznos">
		<restriction base="decimal">
			<minInclusive value="0.00"></minInclusive>
			<totalDigits value="17"></totalDigits>
			<fractionDigits value="2"></fractionDigits>
		</restriction>
	</simpleType>
	<simpleType name="BrojRacuna">
		<restriction base="string">
			<pattern value="[0-9]{3}-[0-9]{13}-[0-9]{2}"></pattern>
		</restriction>
	</simpleType>
	<simpleType name="Model">
		<restriction base="short">
			<minExclusive value="0"></minExclusive>
			<maxExclusive value="100"></maxExclusive>
		</restriction>
	</simpleType>
	<simpleType name="PozivNaBroj">
		<restriction base="string">
			<pattern value="[0-9A-Z]{1,20}"></pattern>
		</restriction>
	</simpleType>
	<complexType name="SredstvoPlacanja" abstract="true">
		<sequence>
			<element name="naziv_duznika" type="tns:NazivSvrha"></element>
			<element name="naziv_povjerioca" type="tns:NazivSvrha"></element>
			<element name="svrha_placanja" type="tns:NazivSvrha"></element>
			<element name="datum_prijema" type="date"></element>
			<element name="datum_izvrsenja" type="date" minOccurs="0"></element>
			<element name="sifra_placanja" type="tns:SifraPlacanja"></element>
			<element name="valuta" type="tns:Valuta"></element>
			<element name="iznos" type="tns:Iznos"></element>
		</sequence>
	</complexType>
	<complexType name="NalogZaUplatu">
		<complexContent>
			<extension base="tns:SredstvoPlacanja">
				<sequence>
					<element name="racun_povjerioca" type="tns:BrojRacuna"></element>
					<element name="model_odobrenja" type="tns:Model" minOccurs="0"></element>
					<element name="poziv_na_broj_odobrenja" type="tns:PozivNaBroj" minOccurs="0"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="NalogZaIsplatu">
		<complexContent>
			<extension base="tns:SredstvoPlacanja">
				<sequence>
					<element name="racun_duznika" type="tns:BrojRacuna"></element>
					<element name="model_zaduzenja" type="tns:Model" minOccurs="0"></element>
					<element name="poziv_na_broj_zaduzenja" type="tns:PozivNaBroj" minOccurs="0"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="NalogZaPrenos">
		<complexContent>
			<extension base="tns:SredstvoPlacanja">
				<sequence>
					<element name="racun_duznika" type="tns:BrojRacuna"></element>
					<element name="model_zaduzenja" type="tns:Model" minOccurs="0"></element>
					<element name="poziv_na_broj_zaduzenja" type="tns:PozivNaBroj" minOccurs="0"></element>
					<element name="racun_povjerioca" type="tns:BrojRacuna"></element>
					<element name="model_odobrenja" type="tns:Model" minOccurs="0"></element>
					<element name="poziv_na_broj_odobrenja" type="tns:PozivNaBroj" minOccurs="0"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<element name="instrumenti_placanja">
		<complexType>
			<sequence>
				<element name="instrument_placanja" maxOccurs="unbounded" type="tns:SredstvoPlacanja"></element>
			</sequence>
		</complexType>
	</element>
</schema>

=== DaniloJevtovic/poslovnaInformatika/project/data.xml
<?xml version="1.0" encoding="UTF-8" ?>
<instrumenti_placanja xmlns="http://www.example.org/instrumenti_placanja" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/instrumenti_placanja instrumenti_placanja.xsd ">
	<instrument_placanja xsi:type="NalogZaUplatu">
		<naziv_duznika>Jovo Jovic</naziv_duznika>
		<naziv_povjerioca>Jovo Jovic</naziv_povjerioca>
		<svrha_placanja>Uplata na personalni racun</svrha_placanja>
		<datum_prijema>2016-06-01</datum_prijema>
		<sifra_placanja>189</sifra_placanja>
		<valuta>RSD</valuta>
		<iznos>20000.00</iznos>
		<racun_povjerioca>123-0000000000000-92</racun_povjerioca>
		<model_odobrenja>97</model_odobrenja>
		<poziv_na_broj_odobrenja>0A</poziv_na_broj_odobrenja>
	</instrument_placanja>
	<instrument_placanja xsi:type="NalogZaPrenos">
		<naziv_duznika>Jovo Jovic</naziv_duznika>
		<naziv_povjerioca>Miro Miric</naziv_povjerioca>
		<svrha_placanja>Slanje novca</svrha_placanja>
		<datum_prijema>2016-06-01</datum_prijema>
		<sifra_placanja>289</sifra_placanja>
		<valuta>RSD</valuta>
		<iznos>3000.00</iznos>
		<racun_duznika>123-0000000000000-92</racun_duznika>
		<model_zaduzenja>75</model_zaduzenja>
		<poziv_na_broj_zaduzenja>8A</poziv_na_broj_zaduzenja>
		<racun_povjerioca>123-0000000000001-89</racun_povjerioca>
		<model_odobrenja>97</model_odobrenja>
		<poziv_na_broj_odobrenja>A4</poziv_na_broj_odobrenja>
	</instrument_placanja>
	<instrument_placanja xsi:type="NalogZaIsplatu">
		<naziv_duznika>Miro Miric</naziv_duznika>
		<naziv_povjerioca>Miro Miric</naziv_povjerioca>
		<svrha_placanja>Podizanje gotovine</svrha_placanja>
		<datum_prijema>2016-06-01</datum_prijema>
		<sifra_placanja>189</sifra_placanja>
		<valuta>RSD</valuta>
		<iznos>2000.00</iznos>
		<racun_duznika>123-0000000000001-89</racun_duznika>
	</instrument_placanja>
	<instrument_placanja xsi:type="NalogZaIsplatu">
		<naziv_duznika>Miro Miric</naziv_duznika>
		<naziv_povjerioca>Miro Miric</naziv_povjerioca>
		<svrha_placanja>Podizanje gotovine</svrha_placanja>
		<datum_prijema>2016-06-01</datum_prijema>
		<sifra_placanja>189</sifra_placanja>
		<valuta>RSD</valuta>
		<iznos>2000.00</iznos>
		<racun_duznika>123-0000000000001-89</racun_duznika>
	</instrument_placanja>
</instrumenti_placanja>
